project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization"
  site-url: "data-visualization/intro.qmd"

  navbar:
    left:
      - text: "R Foundations"
        menu:
          - text: "Getting Started"
            href: r-foundations/getting-started.qmd
          - text: "Data Wrangling (Tidyverse)"
            href: r-foundations/data-wrangling.qmd
      - text: "Data Visualization"
        menu:
          - text: "Best Practices"
            href: data-visualization/best_practices.qmd
          - text: "Grammar of Graphics"
            href: data-visualization/ggplot_grammar.qmd
          - text: "Matching data to plots"
            href: data-visualization/plot_data.qmd
      - text: "Plot Gallery"
        menu:
          - text: "Basic Plots"
            href: plot-gallery/basic.qmd
          - text: "Intermediate Plots"
            href: plot-gallery/moderate.qmd
          - text: "Advanced Plots"
            href: plot-gallery/advanced.qmd
      - text: "Specialized Plots"
        menu:
          - href: specialized/merge_visuals.qmd
            text: "Merged Visuals"
          - href: specialized/plot_stats.qmd
            text: "Statistical Plots"
          - href: specialized/interactive.qmd
            text: "Interactive Plots"
      - text: "Exporting, Tools and Debugging"
        menu:
          - text: "Exporting Plots"
            href: exporting_tools/exporting_plots.qmd
          - text: "Plotting Tools"
            href: exporting_tools/plotting_tools.qmd
          - text: "Debugging Plots"
            href: exporting_tools/debugging_plots.qmd

    right:
      - text: "Reference"
        icon: book
        menu:
          - text: "Contact Us"
            href: contact.qmd
          - text: "References"
            href: references.qmd

  search: true

format:
  html:
    theme: flatly
    css: assets/theme_webp.css
    code-copy: true
    toc: true
    lightbox: auto

